---
title: "Select/Remove based on Pattern"
subtitle: "" 
author: ""
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

## Select data frames based on pattern 

```{r}
thispatternexample <- "example1"
patternexample     <- "example2"
thispattern        <- "example3"

mget(ls(pattern = "pattern"))  #pattern included within (*pattern*)
mget(ls(pattern = "^pattern")) #starts with pattern 
mget(ls(pattern = "pattern$")) #ends with pattern
```

### Special Characters (like `.`)
```{r}
df.1_toprows   <- mtcars[1:2,]
df.2_middle    <- mtcars[3:4,]
df.3_otherrows <- mtcars[5:6, ] 
df4other        <- mtcars[7:8,]

mget(ls(pattern="^df"))
mget(ls(pattern="^df.")) #ignores . (need to denote special character)
mget(ls(pattern="^df\\.")) # use double slash for special character

# can use bind_rows to combine all df's (if they are the same variables) 
dplyr::bind_rows(mget(ls(pattern="^df\\.")))
```


## Remove multiple items by pattern 

```{r, eval = FALSE }
rm(list = ls(pattern = "pattern"))
rm(list = ls(pattern = "^prefix\\."))
rm(list = ls(pattern = "suffix$"))
```